# Workflow for deploying static content to GitHub Pages
name: deploy-pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

# Set permissions for the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Do NOT cancel in-progress runs to allow production deployments to complete
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
      # Step to checkout the repository
      - name: Checkout
        uses: actions/checkout@v3

      # Step to setup Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      # Step to install npm dependencies
      - name: Install dependencies
        run: npm install

      # Step to build the project using gulp
      - name: Build project
        run: npm run build

      # Step to setup GitHub Pages
      - name: Setup Pages
        uses: actions/configure-pages@v3

      # Step to upload the build artifacts to GitHub Pages
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: 'dist'

      # Step to deploy the artifacts to GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
